name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # adjust this to your project's default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # adjust this to your project's required Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build # adjust this if your build command is different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # adjust this to your project's build output directory
